from pathlib import Path
from typing import Self

from pydantic import AnyUrl, Field, HttpUrl, RedisDsn, SecretStr, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic_yaml import parse_yaml_raw_as
from src.entities.content import TableOfContents


class Settings(BaseSettings):

    model_config = SettingsConfigDict(
        # `.env.prod` takes priority over `.env`
        env_file=(".env", ".env.prod")
    )

    download_cache_enabled: bool = Field(
        default=True,
        description="Whether to use the cache for the Wikipedia API",
    )
    download_cache_expire_after: int = Field(
        default=60 * 60 * 24,
        description="The expiration time of the cache in seconds",
    )
    download_start_pages: list[TableOfContents] | None = Field(
        None,
        description="Will be set through the start pages config file",
    )

    start_pages_config: Path | None = Field(
        ...,
        description="""
            The path to the YAML configuration file for the start pages,
            must be provided in the .env file as `START_PAGES_CONFIG`.
        """,
    )

    mediawiki_api_key: str = Field(
        default="",
        description="The API key for the MediaWiki API",
    )
    mediawiki_base_url: str = Field(
        default="https://api.wikimedia.org/core/v1/wikipedia/fr",
        description="The base URL of the Wikipedia API",
    )
    mediawiki_user_agent: str = Field(
        default="Cinefeel",
        description="The user agent to use for the Wikipedia API",
    )

    download_max_concurrency: int = Field(
        default=10,
        description="The maximum number of concurrent connections to download pages",
    )
    download_user_agent: str = Field(
        default="Cinefeel",
        description="The user agent to use for the Wikipedia API",
    )

    meili_base_url: HttpUrl | None = Field(
        default="http://localhost:7700",
        description="The base URL of the MeiliSearch API",
    )
    meili_api_key: str = Field(
        default="cinefeel",
        description="The API key for the MeiliSearch API",
    )
    meili_films_index_name: str = Field(
        default="films",
    )
    meili_persons_index_name: str = Field(
        default="persons",
    )

    persistence_directory: Path = Field(
        default=Path("./data"),
        description="The path (relative or absolute) to the dir where the scraped data will be saved",
    )

    mistral_llm_model: str = Field(
        default="mistral-medium-latest",
    )

    mistral_api_key: SecretStr = Field(
        default="",
        description="The API key for the Mistral API",
    )

    ollama_llm_model: str = Field(
        default="llama3-chatqa:latest",
        description="The name of the LLM model to use for text processing.",
    )

    ollama_vision_model: str = Field(
        default="llava:7b",
        description="""
            The name of the vision model to use for image processing.
            """,
    )

    bert_similarity_model: str = Field(
        default="Lajavaness/sentence-camembert-base",
        description="""
            The name of the BERT model to use for similarity search
        """,
    )

    bert_summary_model: str = Field(
        default="paraphrase-albert-small-v2",
        description="""
            The name of the BERT model to use for summarizing contents.
        """,
    )

    bert_summary_max_length: int = Field(
        default=2000,
        description="""
            The maximum length of the summary generated by the BERT model.
            If the content is longer than this value, it will be truncated.
            Too short summaries would lead to poor results.
        """,
    )

    bert_similarity_threshold: float = Field(
        default=0.9,
        description="""
            The threshold for the BERT similarity score.
            If the score is below this value, the result will be considered as not found.
        """,
    )

    prefect_task_timeout: int = Field(
        default=60 * 30,  # 30 minutes
        description="The timeout for prefect tasks in seconds",
    )
    prefect_concurrency_limit: int = Field(
        default=10,
        description="The maximum number of concurrent prefect tasks",
    )

    # section params
    sections_max_children: int = Field(
        default=3,
        description="""
            The maximum number of children sections per section.
            If a section has more children than this value, the children will be truncated.
        """,
    )
    sections_max_per_page: int = Field(
        default=5,
        description="""
            The maximum number of sections to extract from a page.
            If a page has more sections than this value, the sections will be truncated.
        """,
    )
    sections_min_length: int = Field(
        default=500,
        description="""
            The minimum length of a section.
            If a section is shorter than this value, it will be ignored.
        """,
    )

    graph_db_uri: AnyUrl | None = Field(
        ...,
        description="""
            The URI of the database used to store the graph data.
        """,
    )

    redis_storage_dsn: RedisDsn = Field(
        default="redis://localhost:6379/0",
        description="""
            used for storing html and JSON contents temporarily, before processing them into the Graph DB.
            NB: only the /0 database is supported because we are using RedisSearch module which does not support logical DBs.
            @see https://stackoverflow.com/questions/72116930/redisearch-cannot-create-index-on-db-0
        """,
    )

    @model_validator(mode="after")
    def on_after_init(self) -> Self:

        if not self.start_pages_config or not self.start_pages_config.exists():
            raise ValueError(
                f"start_pages_config is not set or the file does not exist: {self.start_pages_config}"
            )

        with open(self.start_pages_config, "r") as f:
            list_of_tocs = parse_yaml_raw_as(list[TableOfContents], f.read())
            self.download_start_pages = list_of_tocs

        return self
